# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 25 Aug 2017 09:19:29 +0000
*               @ALL          0
*               @user         8
